import { View, Text } from "@react-pdf/renderer";
import { styles } from "./PDFStyles";

export function PDFFooter() {
  const dateStr = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });

  return (
    <View style={styles.footer} fixed>
      <Text style={styles.footerText}>
        Generated by Lumora · {dateStr}
      </Text>
      <Text style={styles.footerBrand}>Lumora</Text>
    </View>
  );
}

